WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000292CBED88D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2dceb91fcbd55f72ee04eab33545430/element
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000292CADF8C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2dceb91fcbd55f72ee04eab33545430/element
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000292CBEDA010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2dceb91fcbd55f72ee04eab33545430/element
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000292CBEDB790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2dceb91fcbd55f72ee04eab33545430/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000292CBEEC550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2dceb91fcbd55f72ee04eab33545430/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000292CBEED450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2dceb91fcbd55f72ee04eab33545430/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000292CCAE1190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2dceb91fcbd55f72ee04eab33545430
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000292CCAE02D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2dceb91fcbd55f72ee04eab33545430
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000292CC8AE090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2dceb91fcbd55f72ee04eab33545430