{"name": "test_with_invalid_password", "status": "broken", "statusDetails": {"message": "NameError: name 'request' is not defined", "trace": "@pytest.fixture(scope=\"function\", autouse=True)\n    def setup_browser():\n>       browser_name = request.config.getoption('browser_name')\nE       NameError: name 'request' is not defined\n\ntests\\conftest.py:32: NameError"}, "start": 1689778573665, "stop": 1689778573665, "uuid": "18c3e104-b8e1-4ff2-bb45-fef01ef16c45", "historyId": "273e45e0bab98340fa9020ed8268d097", "testCaseId": "273e45e0bab98340fa9020ed8268d097", "fullName": "tests.test_signup#test_with_invalid_password", "labels": [{"name": "tag", "value": "web"}, {"name": "feature", "value": "Signing up  with invalid credentials"}, {"name": "story", "value": "Verify that an appropriate error message is displayed and still on same url"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_signup"}, {"name": "host", "value": "LAPTOP-OFQSKCIR"}, {"name": "thread", "value": "2768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_signup"}]}