{"name": "test_with_invalid_password", "status": "broken", "statusDetails": {"message": "AttributeError: module 'urllib.request' has no attribute 'config'", "trace": "@pytest.fixture(scope=\"function\", autouse=True)\n    def setup_browser():\n>       browser_name = request.config.getoption('browser_name')\nE       AttributeError: module 'urllib.request' has no attribute 'config'\n\ntests\\conftest.py:31: AttributeError"}, "start": 1689778385991, "stop": 1689778385991, "uuid": "0ecbfd6a-31e2-43ce-9524-592ae8af46f9", "historyId": "273e45e0bab98340fa9020ed8268d097", "testCaseId": "273e45e0bab98340fa9020ed8268d097", "fullName": "tests.test_signup#test_with_invalid_password", "labels": [{"name": "feature", "value": "Signing up  with invalid credentials"}, {"name": "tag", "value": "web"}, {"name": "story", "value": "Verify that an appropriate error message is displayed and still on same url"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_signup"}, {"name": "host", "value": "LAPTOP-OFQSKCIR"}, {"name": "thread", "value": "16652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_signup"}]}