{"name": "test_with_invalid_email", "status": "broken", "statusDetails": {"message": "NameError: name 'request' is not defined", "trace": "@pytest.fixture(scope=\"function\", autouse=True)\n    def setup_browser():\n>       browser_name = request.config.getoption('browser_name')\nE       NameError: name 'request' is not defined\n\ntests\\conftest.py:32: NameError"}, "start": 1689778573640, "stop": 1689778573640, "uuid": "10ba9831-a9da-463f-8b6a-abe6bd742331", "historyId": "267ad1994ab712361545180c4a21d3b1", "testCaseId": "267ad1994ab712361545180c4a21d3b1", "fullName": "tests.test_signup#test_with_invalid_email", "labels": [{"name": "feature", "value": "Signing up with invalid credentials"}, {"name": "tag", "value": "web"}, {"name": "story", "value": "Verify that an appropriate error message is displayed and still on same url"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_signup"}, {"name": "host", "value": "LAPTOP-OFQSKCIR"}, {"name": "thread", "value": "2768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_signup"}]}