{"name": "test_unsuccessful_login", "status": "broken", "statusDetails": {"message": "AttributeError: module 'urllib.request' has no attribute 'config'", "trace": "@pytest.fixture(scope=\"function\", autouse=True)\n    def setup_browser():\n>       browser_name = request.config.getoption('browser_name')\nE       AttributeError: module 'urllib.request' has no attribute 'config'\n\ntests\\conftest.py:31: AttributeError"}, "start": 1689778385877, "stop": 1689778385877, "uuid": "ec53c5ce-f5b8-4add-9ca0-8228d99774a5", "historyId": "64fa320f84ca13fdf7a1ce2c29801c22", "testCaseId": "64fa320f84ca13fdf7a1ce2c29801c22", "fullName": "tests.test_login#test_unsuccessful_login", "labels": [{"name": "tag", "value": "web"}, {"name": "feature", "value": "Login with invalid data"}, {"name": "story", "value": "Checking if an error is displayed when entering a password that is not in the system"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "LAPTOP-OFQSKCIR"}, {"name": "thread", "value": "16652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}